[network.stream2.task0.subtask0.thread0.block0]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 0
	core_id = 0
	start_cycle = 543
	early_end_cycle = 0
	end_cycle = 791431
	duration = 790888
[network.stream2.task0.subtask0.thread0.block1]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 1
	core_id = 1
	start_cycle = 544
	early_end_cycle = 0
	end_cycle = 832075
	duration = 831531
[network.stream2.task0.subtask0.thread0.block2]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 2
	core_id = 2
	start_cycle = 545
	early_end_cycle = 0
	end_cycle = 168391
	duration = 167846
[network.stream2.task0.subtask0.thread0.block3]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 3
	core_id = 3
	start_cycle = 546
	early_end_cycle = 0
	end_cycle = 8325
	duration = 7779
[network.stream2.task0.subtask0.thread0.block4]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 4
	core_id = 4
	start_cycle = 547
	early_end_cycle = 0
	end_cycle = 8335
	duration = 7788
[network.stream2.task0.subtask0.thread0.block5]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 5
	core_id = 5
	start_cycle = 548
	early_end_cycle = 0
	end_cycle = 8349
	duration = 7801
[network.stream2.task0.subtask0.thread0.block6]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 6
	core_id = 6
	start_cycle = 549
	early_end_cycle = 0
	end_cycle = 8343
	duration = 7794
[network.stream2.task0.subtask0.thread0.block7]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 7
	core_id = 7
	start_cycle = 550
	early_end_cycle = 0
	end_cycle = 8346
	duration = 7796
[network.stream2.task0.subtask0.thread0.block8]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 8
	core_id = 8
	start_cycle = 551
	early_end_cycle = 0
	end_cycle = 8337
	duration = 7786
[network.stream2.task0.subtask0.thread0.block9]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 9
	core_id = 9
	start_cycle = 552
	early_end_cycle = 0
	end_cycle = 8337
	duration = 7785
[network.stream2.task0.subtask0.thread0.block10]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 10
	core_id = 10
	start_cycle = 553
	early_end_cycle = 0
	end_cycle = 8327
	duration = 7774
[network.stream2.task0.subtask0.thread0.block11]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 11
	core_id = 11
	start_cycle = 554
	early_end_cycle = 0
	end_cycle = 8346
	duration = 7792
[network.stream2.task0.subtask0.thread0.block12]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 12
	core_id = 12
	start_cycle = 555
	early_end_cycle = 0
	end_cycle = 8326
	duration = 7771
[network.stream2.task0.subtask0.thread0.block13]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 13
	core_id = 13
	start_cycle = 556
	early_end_cycle = 0
	end_cycle = 8362
	duration = 7806
[network.stream2.task0.subtask0.thread0.block14]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 14
	core_id = 14
	start_cycle = 557
	early_end_cycle = 0
	end_cycle = 8362
	duration = 7805
[network.stream2.task0.subtask0.thread0.block15]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 15
	core_id = 15
	start_cycle = 558
	early_end_cycle = 0
	end_cycle = 8362
	duration = 7804
[network.stream2.task0.subtask0.thread0.block16]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 16
	core_id = 16
	start_cycle = 559
	early_end_cycle = 0
	end_cycle = 8360
	duration = 7801
[network.stream2.task0.subtask0.thread0.block17]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 17
	core_id = 17
	start_cycle = 560
	early_end_cycle = 0
	end_cycle = 8361
	duration = 7801
[network.stream2.task0.subtask0.thread0.block18]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 18
	core_id = 18
	start_cycle = 561
	early_end_cycle = 0
	end_cycle = 8367
	duration = 7806
[network.stream2.task0.subtask0.thread0.block19]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 19
	core_id = 19
	start_cycle = 562
	early_end_cycle = 0
	end_cycle = 8371
	duration = 7809
