[network.stream2.task0.subtask0.thread0.block0]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 0
	core_id = 0
	start_cycle = 548
	early_end_cycle = 0
	end_cycle = 2449973
	duration = 2449425
[network.stream2.task0.subtask0.thread0.block1]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 1
	core_id = 1
	start_cycle = 549
	early_end_cycle = 0
	end_cycle = 899256
	duration = 898707
[network.stream2.task0.subtask0.thread0.block2]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 2
	core_id = 2
	start_cycle = 550
	early_end_cycle = 0
	end_cycle = 292424
	duration = 291874
[network.stream2.task0.subtask0.thread0.block3]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 3
	core_id = 3
	start_cycle = 551
	early_end_cycle = 0
	end_cycle = 8761
	duration = 8210
[network.stream2.task0.subtask0.thread0.block4]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 4
	core_id = 4
	start_cycle = 552
	early_end_cycle = 0
	end_cycle = 8787
	duration = 8235
[network.stream2.task0.subtask0.thread0.block5]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 5
	core_id = 5
	start_cycle = 553
	early_end_cycle = 0
	end_cycle = 8783
	duration = 8230
[network.stream2.task0.subtask0.thread0.block6]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 6
	core_id = 6
	start_cycle = 554
	early_end_cycle = 0
	end_cycle = 8779
	duration = 8225
[network.stream2.task0.subtask0.thread0.block7]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 7
	core_id = 7
	start_cycle = 555
	early_end_cycle = 0
	end_cycle = 8775
	duration = 8220
[network.stream2.task0.subtask0.thread0.block8]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 8
	core_id = 8
	start_cycle = 556
	early_end_cycle = 0
	end_cycle = 8763
	duration = 8207
[network.stream2.task0.subtask0.thread0.block9]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 9
	core_id = 9
	start_cycle = 557
	early_end_cycle = 0
	end_cycle = 8776
	duration = 8219
[network.stream2.task0.subtask0.thread0.block10]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 10
	core_id = 10
	start_cycle = 558
	early_end_cycle = 0
	end_cycle = 8791
	duration = 8233
[network.stream2.task0.subtask0.thread0.block11]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 11
	core_id = 11
	start_cycle = 559
	early_end_cycle = 0
	end_cycle = 8775
	duration = 8216
[network.stream2.task0.subtask0.thread0.block12]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 12
	core_id = 12
	start_cycle = 560
	early_end_cycle = 0
	end_cycle = 8774
	duration = 8214
[network.stream2.task0.subtask0.thread0.block13]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 13
	core_id = 13
	start_cycle = 561
	early_end_cycle = 0
	end_cycle = 8784
	duration = 8223
[network.stream2.task0.subtask0.thread0.block14]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 14
	core_id = 14
	start_cycle = 562
	early_end_cycle = 0
	end_cycle = 8779
	duration = 8217
[network.stream2.task0.subtask0.thread0.block15]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 15
	core_id = 15
	start_cycle = 563
	early_end_cycle = 0
	end_cycle = 8781
	duration = 8218
[network.stream2.task0.subtask0.thread0.block16]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 16
	core_id = 16
	start_cycle = 564
	early_end_cycle = 0
	end_cycle = 8783
	duration = 8219
[network.stream2.task0.subtask0.thread0.block17]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 17
	core_id = 17
	start_cycle = 565
	early_end_cycle = 0
	end_cycle = 8774
	duration = 8209
[network.stream2.task0.subtask0.thread0.block18]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 18
	core_id = 18
	start_cycle = 566
	early_end_cycle = 0
	end_cycle = 8788
	duration = 8222
[network.stream2.task0.subtask0.thread0.block19]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 19
	core_id = 19
	start_cycle = 567
	early_end_cycle = 0
	end_cycle = 8797
	duration = 8230
