[network.stream2.task0.subtask0.thread0.block0]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 0
	core_id = 0
	start_cycle = 308
	early_end_cycle = 0
	end_cycle = 1659353
	duration = 1659045
[network.stream2.task0.subtask0.thread0.block1]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 1
	core_id = 1
	start_cycle = 309
	early_end_cycle = 0
	end_cycle = 923976
	duration = 923667
[network.stream2.task0.subtask0.thread0.block2]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 2
	core_id = 2
	start_cycle = 310
	early_end_cycle = 0
	end_cycle = 322818
	duration = 322508
[network.stream2.task0.subtask0.thread0.block3]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 3
	core_id = 3
	start_cycle = 311
	early_end_cycle = 0
	end_cycle = 8664
	duration = 8353
[network.stream2.task0.subtask0.thread0.block4]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 4
	core_id = 4
	start_cycle = 312
	early_end_cycle = 0
	end_cycle = 8682
	duration = 8370
[network.stream2.task0.subtask0.thread0.block5]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 5
	core_id = 5
	start_cycle = 313
	early_end_cycle = 0
	end_cycle = 8681
	duration = 8368
[network.stream2.task0.subtask0.thread0.block6]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 6
	core_id = 6
	start_cycle = 314
	early_end_cycle = 0
	end_cycle = 8678
	duration = 8364
[network.stream2.task0.subtask0.thread0.block7]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 7
	core_id = 7
	start_cycle = 315
	early_end_cycle = 0
	end_cycle = 8671
	duration = 8356
[network.stream2.task0.subtask0.thread0.block8]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 8
	core_id = 8
	start_cycle = 316
	early_end_cycle = 0
	end_cycle = 8683
	duration = 8367
[network.stream2.task0.subtask0.thread0.block9]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 9
	core_id = 9
	start_cycle = 317
	early_end_cycle = 0
	end_cycle = 8677
	duration = 8360
[network.stream2.task0.subtask0.thread0.block10]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 10
	core_id = 10
	start_cycle = 318
	early_end_cycle = 0
	end_cycle = 8692
	duration = 8374
[network.stream2.task0.subtask0.thread0.block11]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 11
	core_id = 11
	start_cycle = 319
	early_end_cycle = 0
	end_cycle = 8685
	duration = 8366
[network.stream2.task0.subtask0.thread0.block12]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 12
	core_id = 12
	start_cycle = 320
	early_end_cycle = 0
	end_cycle = 8688
	duration = 8368
[network.stream2.task0.subtask0.thread0.block13]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 13
	core_id = 13
	start_cycle = 321
	early_end_cycle = 0
	end_cycle = 8699
	duration = 8378
[network.stream2.task0.subtask0.thread0.block14]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 14
	core_id = 14
	start_cycle = 322
	early_end_cycle = 0
	end_cycle = 8684
	duration = 8362
[network.stream2.task0.subtask0.thread0.block15]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 15
	core_id = 15
	start_cycle = 323
	early_end_cycle = 0
	end_cycle = 8702
	duration = 8379
[network.stream2.task0.subtask0.thread0.block16]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 16
	core_id = 16
	start_cycle = 324
	early_end_cycle = 0
	end_cycle = 8698
	duration = 8374
[network.stream2.task0.subtask0.thread0.block17]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 17
	core_id = 17
	start_cycle = 325
	early_end_cycle = 0
	end_cycle = 8702
	duration = 8377
[network.stream2.task0.subtask0.thread0.block18]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 18
	core_id = 18
	start_cycle = 326
	early_end_cycle = 0
	end_cycle = 8714
	duration = 8388
[network.stream2.task0.subtask0.thread0.block19]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 19
	core_id = 19
	start_cycle = 327
	early_end_cycle = 0
	end_cycle = 8683
	duration = 8356
[network.stream2.task1.subtask0.thread0.block0]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 0
	core_id = 0
	start_cycle = 1675285
	early_end_cycle = 0
	end_cycle = 2723039
	duration = 1047754
[network.stream2.task1.subtask0.thread0.block1]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 1
	core_id = 1
	start_cycle = 1675286
	early_end_cycle = 0
	end_cycle = 2507821
	duration = 832535
[network.stream2.task1.subtask0.thread0.block2]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 2
	core_id = 2
	start_cycle = 1675287
	early_end_cycle = 0
	end_cycle = 1842961
	duration = 167674
[network.stream2.task1.subtask0.thread0.block3]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 3
	core_id = 3
	start_cycle = 1675288
	early_end_cycle = 0
	end_cycle = 1683049
	duration = 7761
[network.stream2.task1.subtask0.thread0.block4]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 4
	core_id = 4
	start_cycle = 1675289
	early_end_cycle = 0
	end_cycle = 1683083
	duration = 7794
[network.stream2.task1.subtask0.thread0.block5]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 5
	core_id = 5
	start_cycle = 1675290
	early_end_cycle = 0
	end_cycle = 1683069
	duration = 7779
[network.stream2.task1.subtask0.thread0.block6]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 6
	core_id = 6
	start_cycle = 1675291
	early_end_cycle = 0
	end_cycle = 1683055
	duration = 7764
[network.stream2.task1.subtask0.thread0.block7]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 7
	core_id = 7
	start_cycle = 1675292
	early_end_cycle = 0
	end_cycle = 1683090
	duration = 7798
[network.stream2.task1.subtask0.thread0.block8]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 8
	core_id = 8
	start_cycle = 1675293
	early_end_cycle = 0
	end_cycle = 1683085
	duration = 7792
[network.stream2.task1.subtask0.thread0.block9]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 9
	core_id = 9
	start_cycle = 1675294
	early_end_cycle = 0
	end_cycle = 1683086
	duration = 7792
[network.stream2.task1.subtask0.thread0.block10]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 10
	core_id = 10
	start_cycle = 1675295
	early_end_cycle = 0
	end_cycle = 1683087
	duration = 7792
[network.stream2.task1.subtask0.thread0.block11]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 11
	core_id = 11
	start_cycle = 1675296
	early_end_cycle = 0
	end_cycle = 1683093
	duration = 7797
[network.stream2.task1.subtask0.thread0.block12]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 12
	core_id = 12
	start_cycle = 1675297
	early_end_cycle = 0
	end_cycle = 1683072
	duration = 7775
[network.stream2.task1.subtask0.thread0.block13]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 13
	core_id = 13
	start_cycle = 1675298
	early_end_cycle = 0
	end_cycle = 1683070
	duration = 7772
[network.stream2.task1.subtask0.thread0.block14]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 14
	core_id = 14
	start_cycle = 1675299
	early_end_cycle = 0
	end_cycle = 1683069
	duration = 7770
[network.stream2.task1.subtask0.thread0.block15]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 15
	core_id = 15
	start_cycle = 1675300
	early_end_cycle = 0
	end_cycle = 1683101
	duration = 7801
[network.stream2.task1.subtask0.thread0.block16]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 16
	core_id = 16
	start_cycle = 1675301
	early_end_cycle = 0
	end_cycle = 1683073
	duration = 7772
[network.stream2.task1.subtask0.thread0.block17]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 17
	core_id = 17
	start_cycle = 1675302
	early_end_cycle = 0
	end_cycle = 1683090
	duration = 7788
[network.stream2.task1.subtask0.thread0.block18]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 18
	core_id = 18
	start_cycle = 1675303
	early_end_cycle = 0
	end_cycle = 1683080
	duration = 7777
[network.stream2.task1.subtask0.thread0.block19]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 19
	core_id = 19
	start_cycle = 1675304
	early_end_cycle = 0
	end_cycle = 1683080
	duration = 7776
