[network.stream2.task0.subtask0.thread0.block0]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 0
	core_id = 0
	start_cycle = 309
	early_end_cycle = 0
	end_cycle = 1675222
	duration = 1674913
[network.stream2.task0.subtask0.thread0.block1]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 1
	core_id = 1
	start_cycle = 310
	early_end_cycle = 0
	end_cycle = 1662998
	duration = 1662688
[network.stream2.task0.subtask0.thread0.block2]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 2
	core_id = 2
	start_cycle = 311
	early_end_cycle = 0
	end_cycle = 944277
	duration = 943966
[network.stream2.task0.subtask0.thread0.block3]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 3
	core_id = 3
	start_cycle = 312
	early_end_cycle = 0
	end_cycle = 930483
	duration = 930171
[network.stream2.task0.subtask0.thread0.block4]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 4
	core_id = 4
	start_cycle = 313
	early_end_cycle = 0
	end_cycle = 343112
	duration = 342799
[network.stream2.task0.subtask0.thread0.block5]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 5
	core_id = 5
	start_cycle = 314
	early_end_cycle = 0
	end_cycle = 328919
	duration = 328605
[network.stream2.task0.subtask0.thread0.block6]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 6
	core_id = 6
	start_cycle = 315
	early_end_cycle = 0
	end_cycle = 73862
	duration = 73547
[network.stream2.task0.subtask0.thread0.block7]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 7
	core_id = 7
	start_cycle = 316
	early_end_cycle = 0
	end_cycle = 73871
	duration = 73555
[network.stream2.task0.subtask0.thread0.block8]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 8
	core_id = 8
	start_cycle = 317
	early_end_cycle = 0
	end_cycle = 73887
	duration = 73570
[network.stream2.task0.subtask0.thread0.block9]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 9
	core_id = 9
	start_cycle = 318
	early_end_cycle = 0
	end_cycle = 73882
	duration = 73564
[network.stream2.task0.subtask0.thread0.block10]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 10
	core_id = 10
	start_cycle = 319
	early_end_cycle = 0
	end_cycle = 73870
	duration = 73551
[network.stream2.task0.subtask0.thread0.block11]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 11
	core_id = 11
	start_cycle = 320
	early_end_cycle = 0
	end_cycle = 73877
	duration = 73557
[network.stream2.task0.subtask0.thread0.block12]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 12
	core_id = 12
	start_cycle = 321
	early_end_cycle = 0
	end_cycle = 73891
	duration = 73570
[network.stream2.task0.subtask0.thread0.block13]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 13
	core_id = 13
	start_cycle = 322
	early_end_cycle = 0
	end_cycle = 73870
	duration = 73548
[network.stream2.task0.subtask0.thread0.block14]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 14
	core_id = 14
	start_cycle = 323
	early_end_cycle = 0
	end_cycle = 73887
	duration = 73564
[network.stream2.task0.subtask0.thread0.block15]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 15
	core_id = 15
	start_cycle = 324
	early_end_cycle = 0
	end_cycle = 73900
	duration = 73576
[network.stream2.task0.subtask0.thread0.block16]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 16
	core_id = 16
	start_cycle = 325
	early_end_cycle = 0
	end_cycle = 73897
	duration = 73572
[network.stream2.task0.subtask0.thread0.block17]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 17
	core_id = 17
	start_cycle = 326
	early_end_cycle = 0
	end_cycle = 73905
	duration = 73579
[network.stream2.task0.subtask0.thread0.block18]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 18
	core_id = 18
	start_cycle = 327
	early_end_cycle = 0
	end_cycle = 73895
	duration = 73568
[network.stream2.task0.subtask0.thread0.block19]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 19
	core_id = 19
	start_cycle = 328
	early_end_cycle = 0
	end_cycle = 73899
	duration = 73571
[network.stream2.task0.subtask0.thread0.block20]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 20
	core_id = 20
	start_cycle = 329
	early_end_cycle = 0
	end_cycle = 73892
	duration = 73563
[network.stream2.task0.subtask0.thread0.block21]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 21
	core_id = 21
	start_cycle = 330
	early_end_cycle = 0
	end_cycle = 73909
	duration = 73579
[network.stream2.task0.subtask0.thread0.block22]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 22
	core_id = 22
	start_cycle = 331
	early_end_cycle = 0
	end_cycle = 73895
	duration = 73564
[network.stream2.task0.subtask0.thread0.block23]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 23
	core_id = 23
	start_cycle = 332
	early_end_cycle = 0
	end_cycle = 73905
	duration = 73573
[network.stream2.task0.subtask0.thread0.block24]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 24
	core_id = 24
	start_cycle = 333
	early_end_cycle = 0
	end_cycle = 73908
	duration = 73575
[network.stream2.task0.subtask0.thread0.block25]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 25
	core_id = 25
	start_cycle = 334
	early_end_cycle = 0
	end_cycle = 73897
	duration = 73563
[network.stream2.task0.subtask0.thread0.block26]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 26
	core_id = 26
	start_cycle = 335
	early_end_cycle = 0
	end_cycle = 73903
	duration = 73568
[network.stream2.task0.subtask0.thread0.block27]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 27
	core_id = 27
	start_cycle = 336
	early_end_cycle = 0
	end_cycle = 73908
	duration = 73572
[network.stream2.task0.subtask0.thread0.block28]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 28
	core_id = 28
	start_cycle = 337
	early_end_cycle = 0
	end_cycle = 73908
	duration = 73571
[network.stream2.task0.subtask0.thread0.block29]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 29
	core_id = 29
	start_cycle = 338
	early_end_cycle = 0
	end_cycle = 73909
	duration = 73571
[network.stream2.task0.subtask0.thread0.block30]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 30
	core_id = 30
	start_cycle = 339
	early_end_cycle = 0
	end_cycle = 73902
	duration = 73563
[network.stream2.task0.subtask0.thread0.block31]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 31
	core_id = 31
	start_cycle = 340
	early_end_cycle = 0
	end_cycle = 73913
	duration = 73573
[network.stream2.task0.subtask0.thread0.block32]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 32
	core_id = 32
	start_cycle = 341
	early_end_cycle = 0
	end_cycle = 73913
	duration = 73572
[network.stream2.task0.subtask0.thread0.block33]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 33
	core_id = 33
	start_cycle = 342
	early_end_cycle = 0
	end_cycle = 73919
	duration = 73577
[network.stream2.task0.subtask0.thread0.block34]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 34
	core_id = 34
	start_cycle = 343
	early_end_cycle = 0
	end_cycle = 73904
	duration = 73561
[network.stream2.task0.subtask0.thread0.block35]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 35
	core_id = 35
	start_cycle = 344
	early_end_cycle = 0
	end_cycle = 73917
	duration = 73573
[network.stream2.task0.subtask0.thread0.block36]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 36
	core_id = 36
	start_cycle = 345
	early_end_cycle = 0
	end_cycle = 73918
	duration = 73573
[network.stream2.task0.subtask0.thread0.block37]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 37
	core_id = 37
	start_cycle = 346
	early_end_cycle = 0
	end_cycle = 73925
	duration = 73579
[network.stream2.task0.subtask0.thread0.block38]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 38
	core_id = 38
	start_cycle = 347
	early_end_cycle = 0
	end_cycle = 73916
	duration = 73569
[network.stream2.task0.subtask0.thread0.block39]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 39
	core_id = 39
	start_cycle = 348
	early_end_cycle = 0
	end_cycle = 73926
	duration = 73578
[network.stream2.task1.subtask0.thread0.block0]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 0
	core_id = 0
	start_cycle = 1675286
	early_end_cycle = 0
	end_cycle = 2734802
	duration = 1059516
[network.stream2.task1.subtask0.thread0.block1]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 1
	core_id = 1
	start_cycle = 1675287
	early_end_cycle = 0
	end_cycle = 2731052
	duration = 1055765
[network.stream2.task1.subtask0.thread0.block2]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 2
	core_id = 2
	start_cycle = 1675288
	early_end_cycle = 0
	end_cycle = 2521620
	duration = 846332
[network.stream2.task1.subtask0.thread0.block3]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 3
	core_id = 3
	start_cycle = 1675289
	early_end_cycle = 0
	end_cycle = 2517323
	duration = 842034
[network.stream2.task1.subtask0.thread0.block4]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 4
	core_id = 4
	start_cycle = 1675290
	early_end_cycle = 0
	end_cycle = 1856614
	duration = 181324
[network.stream2.task1.subtask0.thread0.block5]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 5
	core_id = 5
	start_cycle = 1675291
	early_end_cycle = 0
	end_cycle = 1852751
	duration = 177460
[network.stream2.task1.subtask0.thread0.block6]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 6
	core_id = 6
	start_cycle = 1675292
	early_end_cycle = 0
	end_cycle = 1683950
	duration = 8658
[network.stream2.task1.subtask0.thread0.block7]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 7
	core_id = 7
	start_cycle = 1675293
	early_end_cycle = 0
	end_cycle = 1683956
	duration = 8663
[network.stream2.task1.subtask0.thread0.block8]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 8
	core_id = 8
	start_cycle = 1675294
	early_end_cycle = 0
	end_cycle = 1683949
	duration = 8655
[network.stream2.task1.subtask0.thread0.block9]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 9
	core_id = 9
	start_cycle = 1675295
	early_end_cycle = 0
	end_cycle = 1683957
	duration = 8662
[network.stream2.task1.subtask0.thread0.block10]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 10
	core_id = 10
	start_cycle = 1675296
	early_end_cycle = 0
	end_cycle = 1683955
	duration = 8659
[network.stream2.task1.subtask0.thread0.block11]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 11
	core_id = 11
	start_cycle = 1675297
	early_end_cycle = 0
	end_cycle = 1683949
	duration = 8652
[network.stream2.task1.subtask0.thread0.block12]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 12
	core_id = 12
	start_cycle = 1675298
	early_end_cycle = 0
	end_cycle = 1683946
	duration = 8648
[network.stream2.task1.subtask0.thread0.block13]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 13
	core_id = 13
	start_cycle = 1675299
	early_end_cycle = 0
	end_cycle = 1683958
	duration = 8659
[network.stream2.task1.subtask0.thread0.block14]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 14
	core_id = 14
	start_cycle = 1675300
	early_end_cycle = 0
	end_cycle = 1683956
	duration = 8656
[network.stream2.task1.subtask0.thread0.block15]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 15
	core_id = 15
	start_cycle = 1675301
	early_end_cycle = 0
	end_cycle = 1683968
	duration = 8667
[network.stream2.task1.subtask0.thread0.block16]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 16
	core_id = 16
	start_cycle = 1675302
	early_end_cycle = 0
	end_cycle = 1683956
	duration = 8654
[network.stream2.task1.subtask0.thread0.block17]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 17
	core_id = 17
	start_cycle = 1675303
	early_end_cycle = 0
	end_cycle = 1683973
	duration = 8670
[network.stream2.task1.subtask0.thread0.block18]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 18
	core_id = 18
	start_cycle = 1675304
	early_end_cycle = 0
	end_cycle = 1683969
	duration = 8665
[network.stream2.task1.subtask0.thread0.block19]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 19
	core_id = 19
	start_cycle = 1675305
	early_end_cycle = 0
	end_cycle = 1683975
	duration = 8670
[network.stream2.task1.subtask0.thread0.block20]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 20
	core_id = 20
	start_cycle = 1675306
	early_end_cycle = 0
	end_cycle = 1683991
	duration = 8685
[network.stream2.task1.subtask0.thread0.block21]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 21
	core_id = 21
	start_cycle = 1675307
	early_end_cycle = 0
	end_cycle = 1683964
	duration = 8657
[network.stream2.task1.subtask0.thread0.block22]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 22
	core_id = 22
	start_cycle = 1675308
	early_end_cycle = 0
	end_cycle = 1683963
	duration = 8655
[network.stream2.task1.subtask0.thread0.block23]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 23
	core_id = 23
	start_cycle = 1675309
	early_end_cycle = 0
	end_cycle = 1683975
	duration = 8666
[network.stream2.task1.subtask0.thread0.block24]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 24
	core_id = 24
	start_cycle = 1675310
	early_end_cycle = 0
	end_cycle = 1683964
	duration = 8654
[network.stream2.task1.subtask0.thread0.block25]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 25
	core_id = 25
	start_cycle = 1675311
	early_end_cycle = 0
	end_cycle = 1683980
	duration = 8669
[network.stream2.task1.subtask0.thread0.block26]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 26
	core_id = 26
	start_cycle = 1675312
	early_end_cycle = 0
	end_cycle = 1683987
	duration = 8675
[network.stream2.task1.subtask0.thread0.block27]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 27
	core_id = 27
	start_cycle = 1675313
	early_end_cycle = 0
	end_cycle = 1683960
	duration = 8647
[network.stream2.task1.subtask0.thread0.block28]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 28
	core_id = 28
	start_cycle = 1675314
	early_end_cycle = 0
	end_cycle = 1683982
	duration = 8668
[network.stream2.task1.subtask0.thread0.block29]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 29
	core_id = 29
	start_cycle = 1675315
	early_end_cycle = 0
	end_cycle = 1683981
	duration = 8666
[network.stream2.task1.subtask0.thread0.block30]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 30
	core_id = 30
	start_cycle = 1675316
	early_end_cycle = 0
	end_cycle = 1683979
	duration = 8663
[network.stream2.task1.subtask0.thread0.block31]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 31
	core_id = 31
	start_cycle = 1675317
	early_end_cycle = 0
	end_cycle = 1683989
	duration = 8672
[network.stream2.task1.subtask0.thread0.block32]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 32
	core_id = 32
	start_cycle = 1675318
	early_end_cycle = 0
	end_cycle = 1683972
	duration = 8654
[network.stream2.task1.subtask0.thread0.block33]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 33
	core_id = 33
	start_cycle = 1675319
	early_end_cycle = 0
	end_cycle = 1683981
	duration = 8662
[network.stream2.task1.subtask0.thread0.block34]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 34
	core_id = 34
	start_cycle = 1675320
	early_end_cycle = 0
	end_cycle = 1683982
	duration = 8662
[network.stream2.task1.subtask0.thread0.block35]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 35
	core_id = 35
	start_cycle = 1675321
	early_end_cycle = 0
	end_cycle = 1683999
	duration = 8678
[network.stream2.task1.subtask0.thread0.block36]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 36
	core_id = 36
	start_cycle = 1675322
	early_end_cycle = 0
	end_cycle = 1683992
	duration = 8670
[network.stream2.task1.subtask0.thread0.block37]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 37
	core_id = 37
	start_cycle = 1675323
	early_end_cycle = 0
	end_cycle = 1684000
	duration = 8677
[network.stream2.task1.subtask0.thread0.block38]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 38
	core_id = 38
	start_cycle = 1675324
	early_end_cycle = 0
	end_cycle = 1683980
	duration = 8656
[network.stream2.task1.subtask0.thread0.block39]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 39
	core_id = 39
	start_cycle = 1675325
	early_end_cycle = 0
	end_cycle = 1683997
	duration = 8672
