[network.stream2.task0.subtask0.thread0.block0]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 0
	core_id = 0
	start_cycle = 303
	early_end_cycle = 0
	end_cycle = 3180249
	duration = 3179946
[network.stream2.task0.subtask0.thread0.block1]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 1
	core_id = 1
	start_cycle = 304
	early_end_cycle = 0
	end_cycle = 923181
	duration = 922877
[network.stream2.task0.subtask0.thread0.block2]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 2
	core_id = 2
	start_cycle = 305
	early_end_cycle = 0
	end_cycle = 323267
	duration = 322962
[network.stream2.task0.subtask0.thread0.block3]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 3
	core_id = 3
	start_cycle = 306
	early_end_cycle = 0
	end_cycle = 8670
	duration = 8364
[network.stream2.task0.subtask0.thread0.block4]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 4
	core_id = 4
	start_cycle = 307
	early_end_cycle = 0
	end_cycle = 8674
	duration = 8367
[network.stream2.task0.subtask0.thread0.block5]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 5
	core_id = 5
	start_cycle = 308
	early_end_cycle = 0
	end_cycle = 8665
	duration = 8357
[network.stream2.task0.subtask0.thread0.block6]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 6
	core_id = 6
	start_cycle = 309
	early_end_cycle = 0
	end_cycle = 8678
	duration = 8369
[network.stream2.task0.subtask0.thread0.block7]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 7
	core_id = 7
	start_cycle = 310
	early_end_cycle = 0
	end_cycle = 8679
	duration = 8369
[network.stream2.task0.subtask0.thread0.block8]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 8
	core_id = 8
	start_cycle = 311
	early_end_cycle = 0
	end_cycle = 8682
	duration = 8371
[network.stream2.task0.subtask0.thread0.block9]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 9
	core_id = 9
	start_cycle = 312
	early_end_cycle = 0
	end_cycle = 8662
	duration = 8350
[network.stream2.task0.subtask0.thread0.block10]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 10
	core_id = 10
	start_cycle = 313
	early_end_cycle = 0
	end_cycle = 8674
	duration = 8361
[network.stream2.task0.subtask0.thread0.block11]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 11
	core_id = 11
	start_cycle = 314
	early_end_cycle = 0
	end_cycle = 8680
	duration = 8366
[network.stream2.task0.subtask0.thread0.block12]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 12
	core_id = 12
	start_cycle = 315
	early_end_cycle = 0
	end_cycle = 8669
	duration = 8354
[network.stream2.task0.subtask0.thread0.block13]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 13
	core_id = 13
	start_cycle = 316
	early_end_cycle = 0
	end_cycle = 8693
	duration = 8377
[network.stream2.task0.subtask0.thread0.block14]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 14
	core_id = 14
	start_cycle = 317
	early_end_cycle = 0
	end_cycle = 8694
	duration = 8377
[network.stream2.task0.subtask0.thread0.block15]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 15
	core_id = 15
	start_cycle = 318
	early_end_cycle = 0
	end_cycle = 8678
	duration = 8360
[network.stream2.task0.subtask0.thread0.block16]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 16
	core_id = 16
	start_cycle = 319
	early_end_cycle = 0
	end_cycle = 8675
	duration = 8356
[network.stream2.task0.subtask0.thread0.block17]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 17
	core_id = 17
	start_cycle = 320
	early_end_cycle = 0
	end_cycle = 8703
	duration = 8383
[network.stream2.task0.subtask0.thread0.block18]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 18
	core_id = 18
	start_cycle = 321
	early_end_cycle = 0
	end_cycle = 8693
	duration = 8372
[network.stream2.task0.subtask0.thread0.block19]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	block_id = 19
	core_id = 19
	start_cycle = 322
	early_end_cycle = 0
	end_cycle = 8701
	duration = 8379
[network.stream2.task1.subtask0.thread0.block0]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 0
	core_id = 0
	start_cycle = 3196203
	early_end_cycle = 0
	end_cycle = 5205718
	duration = 2009515
[network.stream2.task1.subtask0.thread0.block1]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 1
	core_id = 1
	start_cycle = 3196204
	early_end_cycle = 0
	end_cycle = 4029393
	duration = 833189
[network.stream2.task1.subtask0.thread0.block2]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 2
	core_id = 2
	start_cycle = 3196205
	early_end_cycle = 0
	end_cycle = 3364118
	duration = 167913
[network.stream2.task1.subtask0.thread0.block3]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 3
	core_id = 3
	start_cycle = 3196206
	early_end_cycle = 0
	end_cycle = 3203990
	duration = 7784
[network.stream2.task1.subtask0.thread0.block4]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 4
	core_id = 4
	start_cycle = 3196207
	early_end_cycle = 0
	end_cycle = 3203988
	duration = 7781
[network.stream2.task1.subtask0.thread0.block5]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 5
	core_id = 5
	start_cycle = 3196208
	early_end_cycle = 0
	end_cycle = 3203988
	duration = 7780
[network.stream2.task1.subtask0.thread0.block6]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 6
	core_id = 6
	start_cycle = 3196209
	early_end_cycle = 0
	end_cycle = 3204007
	duration = 7798
[network.stream2.task1.subtask0.thread0.block7]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 7
	core_id = 7
	start_cycle = 3196210
	early_end_cycle = 0
	end_cycle = 3204013
	duration = 7803
[network.stream2.task1.subtask0.thread0.block8]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 8
	core_id = 8
	start_cycle = 3196211
	early_end_cycle = 0
	end_cycle = 3203989
	duration = 7778
[network.stream2.task1.subtask0.thread0.block9]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 9
	core_id = 9
	start_cycle = 3196212
	early_end_cycle = 0
	end_cycle = 3203975
	duration = 7763
[network.stream2.task1.subtask0.thread0.block10]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 10
	core_id = 10
	start_cycle = 3196213
	early_end_cycle = 0
	end_cycle = 3204007
	duration = 7794
[network.stream2.task1.subtask0.thread0.block11]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 11
	core_id = 11
	start_cycle = 3196214
	early_end_cycle = 0
	end_cycle = 3203971
	duration = 7757
[network.stream2.task1.subtask0.thread0.block12]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 12
	core_id = 12
	start_cycle = 3196215
	early_end_cycle = 0
	end_cycle = 3203996
	duration = 7781
[network.stream2.task1.subtask0.thread0.block13]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 13
	core_id = 13
	start_cycle = 3196216
	early_end_cycle = 0
	end_cycle = 3204018
	duration = 7802
[network.stream2.task1.subtask0.thread0.block14]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 14
	core_id = 14
	start_cycle = 3196217
	early_end_cycle = 0
	end_cycle = 3203991
	duration = 7774
[network.stream2.task1.subtask0.thread0.block15]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 15
	core_id = 15
	start_cycle = 3196218
	early_end_cycle = 0
	end_cycle = 3203985
	duration = 7767
[network.stream2.task1.subtask0.thread0.block16]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 16
	core_id = 16
	start_cycle = 3196219
	early_end_cycle = 0
	end_cycle = 3204030
	duration = 7811
[network.stream2.task1.subtask0.thread0.block17]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 17
	core_id = 17
	start_cycle = 3196220
	early_end_cycle = 0
	end_cycle = 3204023
	duration = 7803
[network.stream2.task1.subtask0.thread0.block18]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 18
	core_id = 18
	start_cycle = 3196221
	early_end_cycle = 0
	end_cycle = 3204004
	duration = 7783
[network.stream2.task1.subtask0.thread0.block19]
	stream_id = 2
	task_id = 1
	subtask_id = 0
	thread_id = 0
	block_id = 19
	core_id = 19
	start_cycle = 3196222
	early_end_cycle = 0
	end_cycle = 3204021
	duration = 7799
[network.stream2.task2.subtask0.thread0.block0]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 0
	core_id = 0
	start_cycle = 5217320
	early_end_cycle = 0
	end_cycle = 6730020
	duration = 1512700
[network.stream2.task2.subtask0.thread0.block1]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 1
	core_id = 1
	start_cycle = 5217321
	early_end_cycle = 0
	end_cycle = 6050578
	duration = 833257
[network.stream2.task2.subtask0.thread0.block2]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 2
	core_id = 2
	start_cycle = 5217322
	early_end_cycle = 0
	end_cycle = 5385533
	duration = 168211
[network.stream2.task2.subtask0.thread0.block3]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 3
	core_id = 3
	start_cycle = 5217323
	early_end_cycle = 0
	end_cycle = 5225109
	duration = 7786
[network.stream2.task2.subtask0.thread0.block4]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 4
	core_id = 4
	start_cycle = 5217324
	early_end_cycle = 0
	end_cycle = 5225094
	duration = 7770
[network.stream2.task2.subtask0.thread0.block5]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 5
	core_id = 5
	start_cycle = 5217325
	early_end_cycle = 0
	end_cycle = 5225100
	duration = 7775
[network.stream2.task2.subtask0.thread0.block6]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 6
	core_id = 6
	start_cycle = 5217326
	early_end_cycle = 0
	end_cycle = 5225118
	duration = 7792
[network.stream2.task2.subtask0.thread0.block7]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 7
	core_id = 7
	start_cycle = 5217327
	early_end_cycle = 0
	end_cycle = 5225130
	duration = 7803
[network.stream2.task2.subtask0.thread0.block8]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 8
	core_id = 8
	start_cycle = 5217328
	early_end_cycle = 0
	end_cycle = 5225128
	duration = 7800
[network.stream2.task2.subtask0.thread0.block9]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 9
	core_id = 9
	start_cycle = 5217329
	early_end_cycle = 0
	end_cycle = 5225108
	duration = 7779
[network.stream2.task2.subtask0.thread0.block10]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 10
	core_id = 10
	start_cycle = 5217330
	early_end_cycle = 0
	end_cycle = 5225136
	duration = 7806
[network.stream2.task2.subtask0.thread0.block11]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 11
	core_id = 11
	start_cycle = 5217331
	early_end_cycle = 0
	end_cycle = 5225110
	duration = 7779
[network.stream2.task2.subtask0.thread0.block12]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 12
	core_id = 12
	start_cycle = 5217332
	early_end_cycle = 0
	end_cycle = 5225132
	duration = 7800
[network.stream2.task2.subtask0.thread0.block13]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 13
	core_id = 13
	start_cycle = 5217333
	early_end_cycle = 0
	end_cycle = 5225137
	duration = 7804
[network.stream2.task2.subtask0.thread0.block14]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 14
	core_id = 14
	start_cycle = 5217334
	early_end_cycle = 0
	end_cycle = 5225139
	duration = 7805
[network.stream2.task2.subtask0.thread0.block15]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 15
	core_id = 15
	start_cycle = 5217335
	early_end_cycle = 0
	end_cycle = 5225139
	duration = 7804
[network.stream2.task2.subtask0.thread0.block16]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 16
	core_id = 16
	start_cycle = 5217336
	early_end_cycle = 0
	end_cycle = 5225136
	duration = 7800
[network.stream2.task2.subtask0.thread0.block17]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 17
	core_id = 17
	start_cycle = 5217337
	early_end_cycle = 0
	end_cycle = 5225127
	duration = 7790
[network.stream2.task2.subtask0.thread0.block18]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 18
	core_id = 18
	start_cycle = 5217338
	early_end_cycle = 0
	end_cycle = 5225141
	duration = 7803
[network.stream2.task2.subtask0.thread0.block19]
	stream_id = 2
	task_id = 2
	subtask_id = 0
	thread_id = 0
	block_id = 19
	core_id = 19
	start_cycle = 5217339
	early_end_cycle = 0
	end_cycle = 5225163
	duration = 7824
